// Navigation items — controlled purely by permissions (section-prefixed)
const navigationItems = [
  {
    header: 'menu.assistantMenu',
    i18n: true,
    permission: 'assistant.view-dashboard',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'assistant-dashboard',
    icon: 'HomeIcon',
    permission: 'assistant.view-dashboard',
  },
  {
    title: 'menu.clients',
    i18n: true,
    route: 'assistant-clients',
    icon: 'UsersIcon',
    permission: 'assistant.view-clients',
  },
  {
    title: 'menu.reservations',
    i18n: true,
    route: 'assistant-reservations',
    icon: 'CalendarIcon',
    permission: 'assistant.view-reservations',
  },
  {
    title: 'menu.waitingQueue',
    i18n: true,
    route: 'assistant-waiting-queue',
    icon: 'ListIcon',
    permission: 'assistant.view-waiting-queue',
  },
  {
    title: 'menu.financials',
    i18n: true,
    route: 'assistant-financials',
    icon: 'DollarSignIcon',
    permission: 'assistant.view-financials',
  },
  {
    title: 'menu.reports',
    i18n: true,
    route: 'assistant-reports',
    icon: 'BarChart2Icon',
    permission: 'assistant.view-reports',
  },
  {
    header: 'menu.doctorMenu',
    i18n: true,
    permission: 'doctor.view-dashboard',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'doctor-dashboard',
    icon: 'HomeIcon',
    permission: 'doctor.view-dashboard',
  },
  {
    title: 'menu.clients',
    i18n: true,
    route: 'doctor-clients',
    icon: 'UsersIcon',
    permission: 'doctor.view-clients',
  },
  {
    title: 'menu.myReservations',
    i18n: true,
    route: 'doctor-reservations',
    icon: 'ClipboardIcon',
    permission: 'doctor.view-reservations',
  },
  {
    title: 'menu.schedule',
    i18n: true,
    route: 'doctor-schedule',
    icon: 'ClockIcon',
    permission: 'doctor.view-schedule',
  },
  {
    title: 'menu.waitingQueue',
    i18n: true,
    route: 'doctor-waiting-queue',
    icon: 'ListIcon',
    permission: 'doctor.view-waiting-queue',
  },
  {
    title: 'menu.financials',
    i18n: true,
    route: 'doctor-financials',
    icon: 'DollarSignIcon',
    permission: 'doctor.view-financials',
  },
  {
    title: 'menu.assistants',
    i18n: true,
    route: 'doctor-assistants',
    icon: 'UserPlusIcon',
    permission: 'doctor.view-assistants',
  },
  {
    title: 'menu.reports',
    i18n: true,
    route: 'doctor-reports',
    icon: 'BarChart2Icon',
    permission: 'doctor.view-reports',
  },
  {
    header: 'menu.adminMenu',
    i18n: true,
    permission: 'admin.view-dashboard',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'admin-dashboard',
    icon: 'HomeIcon',
    permission: 'admin.view-dashboard',
  },
  {
    title: 'menu.rolesPermissions',
    i18n: true,
    route: 'admin-roles',
    icon: 'ShieldIcon',
    permission: 'admin.view-roles',
  },
  {
    header: 'menu.clientMenu',
    i18n: true,
    permission: 'client.view-dashboard',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'dashboard',
    icon: 'HomeIcon',
    permission: 'client.view-dashboard',
  },
]

export default navigationItems
