// Navigation items with i18n translation keys
const navigationItems = [
  {
    header: 'menu.assistantMenu',
    i18n: true,
    resource: 'assistant',
    action: 'read',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'assistant-dashboard',
    icon: 'HomeIcon',
    action: 'read',
    resource: 'assistant',
  },
  {
    title: 'menu.clients',
    i18n: true,
    route: 'assistant-clients',
    icon: 'UsersIcon',
    action: 'read',
    resource: 'assistant',
  },
  {
    title: 'menu.reservations',
    i18n: true,
    route: 'assistant-reservations',
    icon: 'CalendarIcon',
    action: 'read',
    resource: 'assistant',
  },
  {
    title: 'menu.waitingQueue',
    i18n: true,
    route: 'assistant-waiting-queue',
    icon: 'ListIcon',
    action: 'read',
    resource: 'assistant',
  },
  {
    title: 'menu.financials',
    i18n: true,
    route: 'assistant-financials',
    icon: 'DollarSignIcon',
    action: 'read',
    resource: 'assistant',
  },
  {
    title: 'menu.reports',
    i18n: true,
    route: 'assistant-reports',
    icon: 'BarChart2Icon',
    action: 'read',
    resource: 'assistant',
  },
  {
    header: 'menu.doctorMenu',
    i18n: true,
    resource: 'doctor',
    action: 'read',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'doctor-dashboard',
    icon: 'HomeIcon',
    action: 'read',
    resource: 'doctor',
  },
  {
    title: 'menu.myReservations',
    i18n: true,
    route: 'doctor-reservations',
    icon: 'ClipboardIcon',
    action: 'read',
    resource: 'doctor',
  },
  {
    title: 'menu.schedule',
    i18n: true,
    route: 'doctor-schedule',
    icon: 'ClockIcon',
    action: 'read',
    resource: 'doctor',
  },
  {
    title: 'menu.waitingQueue',
    i18n: true,
    route: 'doctor-waiting-queue',
    icon: 'ListIcon',
    action: 'read',
    resource: 'doctor',
  },
  {
    title: 'menu.financials',
    i18n: true,
    route: 'doctor-financials',
    icon: 'DollarSignIcon',
    action: 'read',
    resource: 'doctor',
  },
  {
    title: 'menu.reports',
    i18n: true,
    route: 'doctor-reports',
    icon: 'BarChart2Icon',
    action: 'read',
    resource: 'doctor',
  },
  {
    header: 'menu.clientMenu',
    i18n: true,
    resource: 'client',
    action: 'read',
  },
  {
    title: 'menu.dashboard',
    i18n: true,
    route: 'dashboard',
    icon: 'HomeIcon',
    action: 'read',
    resource: 'client',
  },
]

export default navigationItems
